### ISSUE TITLE
pre-trained model.

### ISSUE THREAD

**Issue by long-wa** [hhb072/STViT#3]
Hi,HHb, I deeply appreciate your work and look forward to your pre-trained model. Let's have mutual encouragement! （*＾-＾*）

**Comment by mywebinfo65536** [comment]
waiting...

**Comment by ZongChen** [comment]
also waiting...

**Comment by xupeijun01** [comment]
waiting...

**Comment by hhb072** [comment]
Thanks for your interest in our work. The pretrained weights has been provided in the following link: https://drive.google.com/drive/folders/1uaT5OarQd9iPrnFufHocHpM3zhyTcetB?usp=drive_link
