### ISSUE TITLE
Loss is NaN when running

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [hhb072/STViT#6]
![image](https://github.com/hhb072/STViT/assets/29570378/eefdfa40-65f4-4782-a094-1342f37595ab)
I do not modifiy any setting, however, the loss is Nan at the very beginning!

**Comment by WangJunjie97** [comment]
me too...

**Comment by lscalala** [comment]
I'm in the same situation. Have you found a solution?

**Comment by hhb072** [comment]
Thank you for pointing out this error. I've corrected the code and also provided the pretrained weights for your convenience.
