### ISSUE TITLE
How to get the learned superpixel tokens?

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [hhb072/STViT#8]
![image](https://github.com/hhb072/STViT/assets/29570378/602ffe14-26db-4bf3-bfdc-f741ec4de60d)
https://github.com/hhb072/STViT/blob/main/models/stvit.py#L249, is pixel_features the learned superpixel tokens? You have already visualized the attention maps, however, how to visualize the learned tokens? Thank you for your help!

**Comment by hhb072** [comment]
Thank you for the reminder. We have uploaded the code for visualizing super tokens, named _visualize_super_tokens.py_, to the _visualization_ folder.
